# Generated by Django 3.0.4 on 2023-01-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.FloatField()),
                ('product_name', models.CharField(max_length=40)),
                ('product_ordered', models.BooleanField(default=False)),
                ('product_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
